### ISSUE TITLE
Support for other Receiver HWIDs

### ISSUE THREAD

**Issue by kgustafson** [dankraus/padawan360#5]
I noticed that you provided support for one 3rd party hwid of 0291 (vice microsoft's default of 0719).  Is it possible to have a method to set this hwid instead?  I ask because I have a receiver that has hwid of 02A9.  If this method existed (to set the hwid) would be able to increase support to other 3rd party wireless receivers (at least support without having to change and recompile the code!)

**Comment by dankraus** [comment]
Thanks for the suggestion @kgustafson 

I'm not interested in writing support by modifying the underlying library right now. I didn't author the library so the support was already there for a few 3rd party receivers. I'd welcome a pull request though. 

I would want comments in the code that calls the method to show the available options to try to make it easy for people that aren't experienced or familiar with the internals to just be as plug and play as possible.
