### ISSUE TITLE
Audio File Links Not Working

### ISSUE THREAD

**Issue by chrisdbais** [dankraus/padawan360#6]
Hi Dan. Both links to the download the audio files for the MPS Trigger are not working. Are you cable to please share the audio files with me. 

https://host-a.net/f/97459-padawanr2soundszip gets a error mkdir /tmp/97459235532753: no space left on device

Thanks

**Comment by dankraus** [comment]
Thanks for letting me know. There was a recent post on Astromech where someone re-hosted them. I've updated the README. They can be found here: https://drive.google.com/drive/folders/19-NO-B2NIjAVUvo6hy9pTMNdYRaIFusJ

**Comment by chrisdbais** [comment]
Thanks Dan. That is big help
